environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

skip_tags: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install bloke-theme-sharp

build: off
test_script:
  - npm test

version: "{build}"
